services:
  yt-cipher:
    image: ghcr.io/kikkia/yt-cipher:master
    container_name: yt-cipher
    restart: always
    environment:
      - API_TOKEN=yt-cipher-token
    networks:
      - lavalink
    ports:
      - "8001:8001"

  lavalink:
    image: fredboat/lavalink:4.2.2
    container_name: lavalink_1
    restart: always
    environment:
      - _JAVA_OPTIONS=-Xmx6G    # set Java options here
      - SERVER_PORT=2333        # set lavalink server port
      - LAVALINK_SERVER_PASSWORD=youshallnotpass    # set password for lavalink
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml   # mount application.yml for lavalink
      - ./plugins/:/opt/Lavalink/plugins/                 # plugins for lavalink
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - 2333:2333
    depends_on:
      - yt-cipher

networks:
  lavalink:
    name: lavalink
