const LANGUAGE_NAMES: Record<string, string> = {
    'en-US': 'English (en-US)',
    'ko-KR': '한국어 (ko-KR)',
    'ru-RU': 'Русский (ru-RU)',
    'sr-RS': 'Српски (sr-RS)',
    'tr-TR': 'Türkçe (tr-TR)',
    'zh-TW': '繁體中文 (zh-TW)',
    'ar': 'العربية (ar)',
    'bg': 'Български (bg)',
    'cs': 'Čeština (cs)',
    'da': 'Dansk (da)',
    'de': 'Deutsch (de)',
    'el': 'Ελληνικά (el)',
    'en-GB': 'English, UK (en-GB)',
    'es-ES': 'Español (es-ES)',
    'es-419': 'Español, LATAM (es-419)',
    'fi': 'Suomi (fi)',
    'fr': 'Français (fr)',
    'he': 'עברית (he)',
    'hi': 'हिन्दी (hi)',
    'hr': 'Hrvatski (hr)',
    'hu': 'Magyar (hu)',
    'id': 'Bahasa Indonesia (id)',
    'it': 'Italiano (it)',
    'ja': '日本語 (ja)',
    'ko': '한국어 (ko)',
    'lt': 'Lietuvių (lt)',
    'nl': 'Nederlands (nl)',
    'no': 'Norsk (no)',
    'pl': 'Polski (pl)',
    'pt-BR': 'Português do Brasil (pt-BR)',
    'ro': 'Română (ro)',
    'ru': 'Русский (ru)',
    'sv-SE': 'Svenska (sv-SE)',
    'th': 'ไทย (th)',
    'tr': 'Türkçe (tr)',
    'uk': 'Українська (uk)',
    'vi': 'Tiếng Việt (vi)',
    'zh-CN': '简体中文 (zh-CN)'
};

export function getLanguageDisplayName(locale: string): string {
    return LANGUAGE_NAMES[locale] ?? locale;
}
